# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  # Couchbase ports
  config.vm.network "forwarded_port", guest: 8091, host: 8091

  # PostgreSQL ports
  config.vm.network :forwarded_port, guest: 5432, host: 5432
  
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end

  # Update system and insall required tools
  config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -q
  SHELL
  
  # Run script to install Ansible
  config.vm.provision "shell", path: "shell/setup-ansible.sh"
  
  # Run Ansible to install target couchbase, mongoDB, postgresql, MariaDB - all should have roughly same config and admin credentials.
  
end
