Vagrant.configure("2") do |config|

  config.vm.define "local" do |local|
    local.vm.provider "virtualbox" do |v|
      v.name = "Local"
    end

    local.vm.box = "ubuntu/trusty64"

    local.vm.provision :ansible do |ansible|
      ansible.playbook = "playbookLocal.yml"
    end
  end

  config.vm.define "data" do |data|
    data.vm.box = "dummy"
    data.vm.synced_folder ".", "/vagrant", disabled: true, type: "rsync"

    data.vm.provider :aws do |aws, override|
      aws.access_key_id = ENV['AWS_KEY']
      aws.secret_access_key = ENV['AWS_SECRET']
      aws.keypair_name = ENV['AWS_KEYNAME']
      aws.ami = 'ami-01f05461' #instancia de Amazon Free Tier con Ubuntu14
      aws.region = 'us-west-2'
      aws.instance_type = 't2.micro'
      aws.security_groups = ["griger_SG_uswest2"]

      aws.tags = {
  		'Name' => 'Data'
      }

      override.vm.box = "dummy"
      override.ssh.username = "ubuntu"
      override.ssh.private_key_path = ENV['AWS_KEYPATH']
    end

    data.vm.provision :ansible do |ansible|
      ansible.playbook = "playbookData.yml"
    end
  end

    config.vm.define "ppal" do |ppal|
      ppal.vm.box = "dummy"
      ppal.vm.synced_folder ".", "/vagrant", disabled: true, type: "rsync"

      ppal.vm.provider :aws do |aws, override|
        aws.access_key_id = ENV['AWS_KEY']
        aws.secret_access_key = ENV['AWS_SECRET']
        aws.keypair_name = ENV['AWS_KEYNAME']
        aws.ami = 'ami-01f05461' #instancia de Amazon Free Tier con Ubuntu14
        aws.region = 'us-west-2'
        aws.instance_type = 't2.micro'
        aws.security_groups = ["griger_SG_uswest2"]

        aws.tags = {
    		'Name' => 'Ppal'
        }

        override.vm.box = "dummy"
        override.ssh.username = "ubuntu"
        override.ssh.private_key_path = ENV['AWS_KEYPATH']
      end

      ppal.vm.provision :ansible do |ansible|
        ansible.playbook = "playbookPpal.yml"
      end
    end
end
