# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "https://vagrantcloud.com/ubuntu/trusty64"
  config.vm.provision :shell, :path => "shell.sh"

	config.vm.provider :virtualbox do |vb, override|
    ## Forward ports

    # IPython Notebook
    override.vm.network :forwarded_port, host: 8888, guest: 8888

    # Rstudio server
    override.vm.network :forwarded_port, host: 8787, guest: 8787

    # MongoDB
    config.vm.network "forwarded_port", guest: 3000, host: 3000
    config.vm.network "forwarded_port", guest: 27017, host: 27017

	end
  
  config.vm.provider "virtualbox" do |vb|
  	#vb.customize ["modifyvm", :id, "--vram", "100"]
    vb.customize ["modifyvm", :id, "--memory", "4000"]
  end
end
