# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # jj 2013-07-17 my concise Vagrantfile

  # specify base box configuration

  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  # add our provisions

  config.vm.provision :shell, :path => "provision.sh"

  # we use port 5000 for node.js testing

  config.vm.network :forwarded_port, guest: 5000, host: 5000

  # for graphical development, forward x11
  # remember to "xhosts +10.0.0.2" on host machine

  # config.ssh.forward_x11 = true

end
